# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f0e5a0d1bb9bcc949ec594c9d512f8f9b25ee8db5bfc834277c8892bf82a631cfd2a4bcbfdf842705840827d1a2c3790d2faedd0680a19001e1e488df77b9c

test:
  secret_key_base: c3687741b45f501bfa73fc238eec136d0ca888f6fc534a356e9923ce85abb6e7dff86d9c7e7d12a666329d928166e8cd7e9a71b1091862fb77b7f5e5750398a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
